FROM ubuntu:latest

RUN apt-get update && \
    apt-get install -qy \
         python3 \
         python3-pip

RUN pip3 install http://download.pytorch.org/whl/cu75/torch-0.2.0.post3-cp35-cp35m-manylinux1_x86_64.whl
